#!/bin/bash

fail=

vmdir=$PWD/tmp
rm -fr $vmdir
mkdir -p $vmdir

passwordcmd="echo PASSWORD"
hostip="192.168.1.10"
hostiface="eth5"

export root passwordcmd hostip hostiface
. ../bin/vm.config
config.init

mkdir -p $confdir/keys
touch $confdir/keys/testkey

function compare() {
	local name=$1
	local scenario=$2
	local actual="${3:-$vmdir/actual.$name}"
	local source="expect.$name/$scenario"
	local expected="${4:-$vmdir/expect.$name}"

	if [ ! -f $expected ];
	then
	    cat $source | sed "s,@@LXCROOT@@,${vmdir},g" > $expected
	fi

	diff -w $actual $expected
	if [ $? -eq 0 ];
	then
		echo "$name : $scenario : [PASSED]"
	else
		echo -e "$name : $scenario : [FAILED]\n\n"
		fail=true
	fi
}

. ../bin/vm.info somenode --test | sed 's/\\/\\/g' > $vmdir/actual.vm.info
compare vm.info out

. ../bin/vm.new testnode --test | sed 's/\\/\\/g' > $vmdir/actual.vm.new
compare vm.new out

mkdir $vmdir/webserver
. ../bin/vm.new webnode webserver --test | sed 's/\\/\\/g' > $vmdir/actual.vm.new-ephemeral
compare vm.new-ephemeral out

. ../bin/vm.start testnode --test | sed 's/\\/\\/g' > $vmdir/actual.vm.start
compare vm.start out

. ../bin/vm.start webserver --test | sed 's/\\/\\/g' > $vmdir/actual.vm.start-ephemeral
compare vm.start-ephemeral out

. ../bin/vm.delete testnode --test | sed 's/\\/\\/g' > $vmdir/actual.vm.delete
compare vm.delete out

mountcmd="echo $vmdir/enode"
. ../bin/vm.delete enode webserver --test | sed 's/\\/\\/g' > $vmdir/actual.vm.delete-ephemeral
compare vm.delete-ephemeral out

. ../bin/vm.stop testnode --test | sed 's/\\/\\/g' > $vmdir/actual.vm.stop
compare vm.stop out

. ../bin/vm.clone webserver newnode --test | sed 's/\\/\\/g' > $vmdir/actual.vm.clone
compare vm.clone out

ln -sf $vmdir/webserver $vmdir/linkserver
. ../bin/vm.clone linkserver newnode --test | sed 's/\\/\\/g' > $vmdir/actual.vm.clone-softlink
compare vm.clone-softlink out

if [ "$fail" != "" ];
then
    exit 1
fi







