#!/bin/bash

fail=

vmdir=$PWD/tmp
rm -fr $vmdir
mkdir -p $vmdir

passwordcmd="echo PASSWORD"
hostip="192.168.1.10"
hostiface="eth5"

export root passwordcmd hostip hostiface
. ../.bin/vm.config
config.init

mkdir -p $confdir/keys
touch $confdir/keys/testkey

function compare() {
	local name=$1
	local scenario=$2
	local actual="${3:-$vmdir/actual.$name}"
	local source="expect.$name/$scenario"
	local expected="${4:-$vmdir/expect.$name}"

	if [ ! -f $expected ];
	then
	    cat $source | sed "s,@@LXCROOT@@,${vmdir},g" > $expected
	fi

	diff -w $actual $expected
	if [ $? -eq 0 ];
	then
		echo "$name : $scenario : [PASSED]"
	else
		echo "$name : $scenario : [FAILED]"
		fail=true
	fi
}

. ../.bin/vm.new testnode --test | sed 's/\\/\\/g' > $vmdir/actual.vm.new
compare vm.new out 

. ../.bin/vm.delete testnode --test | sed 's/\\/\\/g' > $vmdir/actual.vm.delete
compare vm.delete out

if [ "$fail" != "" ];
then
    exit 1
fi







